# Generated by Django 3.0.8 on 2020-07-09 21:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200708_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='birthdate',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='notedate',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='note',
            name='text',
        ),
        migrations.AddField(
            model_name='note',
            name='note',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contacts.Contact'),
        ),
    ]
